### ISSUE TITLE
Update to gulp-sass 5

### ISSUE THREAD

**Issue by wallace41290** [heyymarco/tilde-sass#1]
Any chance you could update to use gulp-sass 5 so that it doesn't have a dependency on node-sass? Anytime I install tilde-sass into my project, it pulls in a dependency on node-sass and starts using that instead, which breaks builds for me.

**Comment by heyymarco** [comment]
updated for supporting postcss 8 & gulp 5.

sorry for late response (almost a year :p). i'm busy working on another projects.
