### ISSUE TITLE
Node API usage?

### ISSUE THREAD

**Issue by dmackerman** [heyymarco/tilde-sass#2]
Is it possible to use this inside of Node scripts?

**Comment by heyymarco** [comment]
tilde-sass is actually a wrapper of gulp + postcss + custom poscss plugin.
The plugin is: 'postcss-merge-rules-plus' : https://www.npmjs.com/package/postcss-merge-rules-plus

Maybe you dont need a gulp. You can use postcss + the plugin.

**Comment by dmackerman** [comment]
Thanks.
